### ISSUE TITLE
name 'os' is not defined

### ISSUE THREAD

**Issue by Q78KG** [alembics/disco-diffusion#123]
When I used it in colab, it reported an error. Here is the log.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-e397650c0683> in <module>()
     93 
     94 # Download the diffusion model(s)
---> 95 download_model(diffusion_model)
     96 if use_secondary_model:
     97     download_model('secondary')

1 frames
<ipython-input-1-e397650c0683> in get_model_filename(diffusion_model_name)
     59 def get_model_filename(diffusion_model_name):
     60     model_uri = diff_model_map[diffusion_model_name]['uri_list'][0]
---> 61     model_filename = os.path.basename(urlparse(model_uri).path)
     62     return model_filename
     63 

NameError: name 'os' is not defined

**Comment by Q78KG** [comment]
This appears when I try to run the 2.diffusion and clip model settings cell.

**Comment by aletts** [comment]
Try selecting "Runtime -> Run all" from the Colab menu. That'll run all the cells from the top. When unusual errors like this are seen, it's usually because all the cells haven't been run in order from the top.
If further unusual errors are seen, it can be a good idea to terminate the instance and select Runtime -> Run all from the top.

**Comment by Q78KG** [comment]
In fact, I clicked "Run All" while I was running, and I only opened the issue after I tried it. I checked the code of the colab notebook before running it and it was intact. The colab notebook I use is the link in readme.
Emmmm… I used a translator, so what I said might be a little weird.

**Comment by Q78KG** [comment]
I have solved this problem, it should be the problem with the device I am using, although it sounds a little strange, but the problem disappeared after I replaced the device. Thank you for your answer.
