### ISSUE TITLE
Files 404

### ISSUE THREAD

**Issue by 15615901307** [alembics/disco-diffusion#132]
docker build -t disco-diffusion-prep:5.1 .      

https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt

https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth

Can you upload these two files, or share the new download address?

**Comment by aletts** [comment]
I've just merged a fix from deltaflops which is likely to fix this.
