### ISSUE TITLE
ModuleNotFoundError: No module named 'py3d_tools'

### ISSUE THREAD

**Issue by hsk77** [alembics/disco-diffusion#22]
Hi, there is an issue from "1.5 Define necessary functions"

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-a843ec915145>](https://localhost:8080/#) in <module>()
      4 
      5 import pytorch3d.transforms as p3dT
----> 6 import disco_xform_utils as dxf
      7 
      8 def interp(t):

[/content/disco_xform_utils.py](https://localhost:8080/#) in <module>()
      1 import torch, torchvision
----> 2 import py3d_tools as p3d
      3 import midas_utils
      4 from PIL import Image
      5 import numpy as np

ModuleNotFoundError: No module named 'py3d_tools'

**Comment by jakubknejzlik** [comment]
👍  for me as well. Unfortunately as the script pulls from git repo on main branch, it broke probably all the copied colabs. I have to run on my own fork: https://github.com/jakubknejzlik/disco-diffusion

Note: maybe some sort of releases would be nice to avoid breaking copied colabs :)

**Comment by MSFTserver** [comment]
@jakubknejzlik @hsk77 this should be resolved now, was mistake of forgetting to compile a new ipynb against my pytorch3d lite PR

_Sent from my SM-G988U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jakubknejzlik** [comment]
@MSFTserver tested and works! Thanks for such quick response :)

**Comment by hsk77** [comment]
Thanks to all of you. It works
