### ISSUE TITLE
Can someone tell me how to get disco-diffusion V5.1?

### ISSUE THREAD

**Issue by AI-Ahmed** [alembics/disco-diffusion#46]
After V5.2 was released, I found issues related to my notebook since I was dealing with the custom one I did. Can someone tell me how to install V5.1 on my notebook?

**Comment by aletts** [comment]
You can view the full history of the notebook here: https://github.com/alembics/disco-diffusion/commits/e4754e6a42743448fddd0c9a4d81c906ebd48456/Disco_Diffusion.ipynb

Beside each commit, there's a "View at this point in the history" button (this is its hover text if you hover over it for a moment). You can select the version you want. After that, an "Open in Colab" button appears after a short delay which you can use to open it in Colab. Alternatively, you can right-click download the version from that time via the "Raw" button.
If you're interested in merging with your code, I'm not sure. We're not separately maintaining older versions of the notebook.

**Comment by AI-Ahmed** [comment]
> You can view the full history of the notebook here: https://github.com/alembics/disco-diffusion/commits/e4754e6a42743448fddd0c9a4d81c906ebd48456/Disco_Diffusion.ipynb
> 
> Beside each commit, there's a "View at this point in the history" button (this is its hover text if you hover over it for a moment). You can select the version you want. After that, an "Open in Colab" button appears after a short delay which you can use to open it in Colab. Alternatively, you can right-click download the version from that time via the "Raw" button. If you're interested in merging with your code, I'm not sure. We're not separately maintaining older versions of the notebook.

Thank you @aletts for answering me. I don't need the notebook version, I need the best commit for V5.1 to clone the package from if you can, please.

**Comment by aletts** [comment]
v5.1 can be a confusing thing, since we haven't been careful with versioning. We made some changes to v5.1 without bumping up the version number. Therefore I can't be sure which version of v5.1 you'd want. You'd have to compare what's in each of the commits during the v5.1 timeframe and pick the one corresponding to the code that you're working with.
(Maybe you'd want the original v5.1, or maybe you'd want one of the later patched versions of v5.1)

**Comment by aletts** [comment]
Comparing the changelog in your version of the code versus what's in each commit may be one of the easiest ways to narrow things down.

**Comment by AI-Ahmed** [comment]
Thank you @aletts again for answering me. I want the commit before adding VR.

I think the last commit is from 10 or 12 days.

If you can please send it to me with the clone command, I would really appreciate that since I tried different types of a commit but I was not able to clone any of them.

thank you, again!

**Comment by DylanKojiCheslin** [comment]
if the version you want is in google colab and existed in the past 31 days it can be retrieved from google drive.  
 https://support.google.com/a/users/answer/9308971?hl=en
