### ISSUE TITLE
How large is the project?

### ISSUE THREAD

**Issue by oretsuyoi** [alembics/disco-diffusion#64]
last night,I installed docker-for-windows,then changed directory to [docker/prep],executing [docker build -t disco-diffusion-prep:5.1 .] command.At first,it was running succesffully,I was so glad.One hour later,I saw the progressbar stucked at 3/19,only time growing and data remianing still.Two hours later,it was the same.And I noticed that it took me nearly 15 GB on C: disk building the project which failed to build.

**Comment by entmike** [comment]
It'll take about 30GB during the build process because it embeds all the required model files.  Also if you are on Windows, make sure you have WSL2 and GPU passthru.
