### ISSUE TITLE
Models links are broken / Invalid S3 Bucket

### ISSUE THREAD

**Issue by sigmaprojects** [alembics/disco-diffusion#66]
It seems the s3 bucket for the models is broken, error: NoSuchBucket
https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt
https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth

**Comment by samedii** [comment]
One of them has been moved here
https://the-eye.eu/public/AI/models/v-diffusion/secondary_model_imagenet_2.pth

**Comment by sigmaprojects** [comment]
I also came across the 512 model hosted at https://huggingface.co/lowlevelware/512x512_diffusion_unconditional_ImageNet/resolve/main/512x512_diffusion_uncond_finetune_008100.pt

**Comment by MSFTserver** [comment]
Fixed in #67, just waiting for to be merged

**Comment by sigmaprojects** [comment]
Closing for now, hope these links last - mostly concerned about the-eye.
Any chance we can move these files elsewhere, like a separate GitHub repo?

**Comment by voodoohop** [comment]
I was having trouble with the dropbox links so hosting them through IPFS:

https://bafybeibaawhhk7fhyhvmm7x24zwwkeuocuizbqbcg5nqx64jq42j75rdiy.ipfs.nftstorage.link/ipfs/bafybeibaawhhk7fhyhvmm7x24zwwkeuocuizbqbcg5nqx64jq42j75rdiy/512x512_diffusion_uncond_finetune_008100.pt
https://bafybeibaawhhk7fhyhvmm7x24zwwkeuocuizbqbcg5nqx64jq42j75rdiy.ipfs.nftstorage.link/ipfs/bafybeibaawhhk7fhyhvmm7x24zwwkeuocuizbqbcg5nqx64jq42j75rdiy/secondary_model_imagenet_2.pth

**Comment by MSFTserver** [comment]
@voodoohop yea we tapped out the 400gb bandwidth limit within like 2 hours. Aparantly this is used way more than we thought

_Sent from my SM-G988U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by voodoohop** [comment]
> @voodoohop yea we tapped out the 400gb bandwidth limit within like 2 hours. Aparantly this is used way more than we thought

@MSFTserver I just edited the links to not use Pollinations' IPFS gateway since we could end up paying a lot of bandwidth cost. I changed it to use Cloudflare. 

Feel free to use those if you still need a stable set of links. They shouldn't go offline since they're pinned to IPFS.
