### ISSUE TITLE
Howdy, just noticed a type0 in the main description

### ISSUE THREAD

**Issue by aztecman** [alembics/disco-diffusion#72]
"v3 Update: Dec 24th 2021 - Somnai"
...
"v4 Update: Jan 2021 - Somnai" [<-- I'm wagering this should be 2022]
...
"v4.1 Update: Jan 14th 2021 - Somnai" [<-- Same for this line]
...
"v5 Update: Feb 20th 2022 - gandamu / Adam Letts"

**Comment by aletts** [comment]
Hehe, yes. You're right. In early 2022, Somnai was still forgetting the year had changed (I do that a lot too..).

**Comment by aletts** [comment]
Fixed
