### ISSUE TITLE
init_image not working

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [alembics/disco-diffusion#81]
After setting an init_image I'm getting the following error. The image does exist inside the init_images folder in google drive. 
![imagen](https://user-images.githubusercontent.com/5278928/169301216-bc5cec1f-6261-4f68-83e0-52e7a14a0373.png)

`FileNotFoundError: [Errno 2] No such file or directory: 'darth.png'`

**Comment by ryuzaki01** [comment]
Init image should be a direct link to a URL, good luck

**Comment by dngrlux** [comment]
Your path may be something similar to /content/drive/MyDrive/AI/Disco_Diffusion/init_images/filename.png

You can copy that path from the interface itself by clicking on the small folder icon in the leftmost panel. Then go to drive, my drive, AI, Disco_Diffusion, init_images, find the image you want and click on the three vertical dots to 'Copy path'. Paste that path into the init_image field to the right.
