### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Rakeson** [alembics/disco-diffusion#83]
in 4 diffuse!
![SX1BIDKQMT19KST D(FYU%V](https://user-images.githubusercontent.com/78890760/169630900-5f5462fc-0bc0-4d6c-9a23-870a128825d1.png)
![AU6$C1DP}G}O2 3N28D)~40](https://user-images.githubusercontent.com/78890760/169630938-340e9279-5acf-45af-a026-7c5696927604.png)
![N}N8RU6E_J6ZTUYLB%N 2G8](https://user-images.githubusercontent.com/78890760/169630940-dcd908ce-77c0-4a9a-bd64-a9bfef467972.png)

**Comment by Rakeson** [comment]
I have stuck in here for few hours, why things were OK in yesterday? (ran it for 4 to 5 hours)

**Comment by Rakeson** [comment]
![D})M}M38_R296413XNA}8DU](https://user-images.githubusercontent.com/78890760/169645725-07f41bba-68fd-4933-9fc3-f1b25acfa156.png)
after multiple tests, this yellow notification will also shown up at the same time

**Comment by aletts** [comment]
@Rakeson People who use negative weights in their text prompts encounter that error when their weights sum to 0. Apologies for that -- the code is old, silly code which was probably written without consideration for negative weights.

When you know the problem, it's easy to work around it. For any prompts where you don't specify a weight, its weight is 1. If you've got just two prompts where has a weight of -1 , then you can give the other one a weight of 2 and it'll work.

**Comment by Rakeson** [comment]
But wait it was fine when I typed "bla bla bla","human:-2"
but when it was "bla bla bla","human:-2","no any words" and "bla bla bla","no any words","human:-2",these two kinds will show the Runtime error. Why the first time (above) was fine but its weight is -2?

**Comment by Rakeson** [comment]
Which this means? I should gather these elements instead of spreading them sperate?

**Comment by aletts** [comment]
@Rakeson As long as the prompt weights don't sum to 0, it'll run. I've seen people suggest turning the weight to -2.. and the effect of that is usually that they'll have it sum to -1 (if there were two prompts and the other is the default 1). I prefer to increase a positive weight in order to have them sum to something positive (since it seems less ridiculous), but it probably doesn't matter either way.

**Comment by Rakeson** [comment]
OK, I will keep trying

**Comment by Rakeson** [comment]
I found out that I can customize whatever I want in the first "" but after it you have to make every part containing weight number
