### ISSUE TITLE
Are there any related papers?

### ISSUE THREAD

**Issue by Josh00-Lu** [alembics/disco-diffusion#85]
Is there any related papers? Curious about how it work and trained

**Comment by aletts** [comment]
There are at least a couple OpenAI papers that are directly involved. These are good starting points.. and there are good links throughout and in the citations.

CLIP - Learning Transferable Visual Models From Natural Language Supervision: https://arxiv.org/abs/2105.05233
Diffusion - Diffusion Models Beat GANs on Image Synthesis: https://arxiv.org/abs/2105.05233
