### ISSUE TITLE
512x512_diffusion_uncond_finetune_008100.pt not find

### ISSUE THREAD

**Issue by easyplux** [alembics/disco-diffusion#88]
https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt

when i build docker this is error: 512x512_diffusion_uncond_finetune_008100.pt not find from aws

**Comment by Mohan-Zhang-u** [comment]
for those who cannot get the file from huggingface, you may want to try with
```wget https://the-eye.eu/public/AI/models/512x512_diffusion_unconditional_ImageNet/512x512_diffusion_uncond_finetune_008100.pt```

**Comment by aletts** [comment]
Thanks. @Mohan-Zhang-u : Coincidentally, someone DM'd me about this today and I resolved the problem by changing the primary download link for the 512x512 to the-eye.eu (instead of an S3 source). So it was a good suggestion.
