### ISSUE TITLE
TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'

### ISSUE THREAD

**Issue by Limbicnation** [alembics/disco-diffusion#94]
```
Output()
Seed used: 1633703214
Traceback (most recent call last):
  File "disco.py", line 2607, in <module>
    do_run()
  File "disco.py", line 1338, in do_run
    samples = sample_fn(
TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'
```

**Comment by aletts** [comment]
If you're running locally and have previously cached the guided-diffusion code from https://github.com/crowsonkb/guided-diffusion/ , you'll need to instead clone from https://github.com/kostarion/guided-diffusion/
cut_pow added the transformation_fn functionality (required for v5.3's new symmetry implementation) under kostarion.

**Comment by Limbicnation** [comment]
@aletts  Thank you very much! That solved the problem, great work!

**Comment by BeaverInGreenland** [comment]
> If you're running locally and have previously cached the guided-diffusion code from https://github.com/crowsonkb/guided-diffusion/ , you'll need to instead clone from https://github.com/kostarion/guided-diffusion/ cut_pow added the transformation_fn functionality (required for v5.3's new symmetry implementation) under kostarion.

Hello, I met the same issue, but I don't have guided-diffusion within the disco-diffusion's director. What should I do ?

**Comment by BeaverInGreenland** [comment]
> > If you're running locally and have previously cached the guided-diffusion code from https://github.com/crowsonkb/guided-diffusion/ , you'll need to instead clone from https://github.com/kostarion/guided-diffusion/ cut_pow added the transformation_fn functionality (required for v5.3's new symmetry implementation) under kostarion.
> 
> Hello, I met the same issue, but I don't have guided-diffusion within the disco-diffusion's folder. What should I do ? I cloned guided-diffusion within disco-diffusion. It didn't fix the problem

I think I may have found a solution that works:  
- I cloned kostarion's **guided-diffusion** repository within my disco-diffusion repo. 
- I renamed guided-diffusion -> guideddiffusion. 
- I changed the following line in disco.py `from guided_diffusion.script_util import create_model_and_diffusion, model_and_diffusion_defaults` to `from guideddiffusion.guided_diffusion.script_util import create_model_and_diffusion, model_and_diffusion_defaults`
